module.exports = {
  apps: [
    {
      name: 'zaytoonz-ngo',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/zaytoonz-ngo',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_file: '/var/www/zaytoonz-ngo/.env',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/log/pm2/zaytoonz-ngo-error.log',
      out_file: '/var/log/pm2/zaytoonz-ngo-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'python-scraper',
      script: 'venv/bin/uvicorn',
      args: 'api_wrapper:app --host 0.0.0.0 --port 8000 --loop asyncio',
      cwd: '/var/www/zaytoonz-ngo/Scrape_Master',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env_file: '/var/www/zaytoonz-ngo/.env',
      env: {
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
      },
      error_file: '/var/log/pm2/python-scraper-error.log',
      out_file: '/var/log/pm2/python-scraper-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'nlweb',
      script: 'venv/bin/python',
      args: 'app-file.py',
      cwd: '/var/www/zaytoonz-ngo/NLWeb-main/code/python',
      interpreter: 'none',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '2G',
      env_file: '/var/www/zaytoonz-ngo/NLWeb-main/.env',
      env: {
        PYTHONUNBUFFERED: '1',
        PYTHONDONTWRITEBYTECODE: '1',
        PORT: 8001,
        PYTHONPATH: '/var/www/zaytoonz-ngo/NLWeb-main/code/python',
        NLWEB_CONFIG_DIR: '/var/www/zaytoonz-ngo/NLWeb-main/config',
        NLWEB_OUTPUT_DIR: '/var/www/zaytoonz-ngo/NLWeb-main/data/nlweb',
      },
      error_file: '/var/log/pm2/nlweb-error.log',
      out_file: '/var/log/pm2/nlweb-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ],
};

